### ISSUE TITLE
Stopping after PIE hangs the editor

### ISSUE THREAD

**Issue by coreyx** [ue4plugins/NdiMedia#3]
Pressing the stop button while in PIE mode with an active NDI source seems to hang the editor for a good 60 seconds or more. 

Using UE 4.14 and the latest commit [1bf010b](https://github.com/ue4plugins/NdiMedia/commit/1bf010b00248aa74c56c304667fdbd6382226b20)

**Comment by gmpreussner** [comment]
I was able to repro. I'll take a look.

**Comment by gmpreussner** [comment]
Should be fixed. Let me know if you run into any other issues, thanks!

**Comment by coreyx** [comment]
I think it's still deadlocking. I pulled and tried out the latest commit, but my editor is still hanging for a long time after stopping PIE.

**Comment by coreyx** [comment]
Actually, I'm not entirely positive it is still deadlocking. One project I updated was still exhibiting that behavior, but another one wasn't. I'll try to recompile the project that was failing again. However, I found another issue. Audio is out of sync with the video. I'm going to file a separate issue.

**Comment by coreyx** [comment]
Okay, I haven't been able to reproduce either the deadlocking or the audio sync issue with the latest version [693233d](https://github.com/ue4plugins/NdiMedia/commit/693233dd55291a596377500a4f7608dafd6e35e0) as of yet. However, I discovered another issue [#4](https://github.com/ue4plugins/NdiMedia/issues/4) with audio failing to play after starting and stopping PIE a number of times.

**Comment by kzoink** [comment]
I've been running into more deadlocking when pressing stopping PIE mode with the latest version [693233d](https://github.com/ue4plugins/NdiMedia/commit/693233dd55291a596377500a4f7608dafd6e35e0). I think this should be reopened.

**Comment by coreyx** [comment]
I've been running into more intermittent deadlocking which results in the editor hanging for long periods of time when pressing stop after playing in PIE mode with the latest version [693233d](https://github.com/ue4plugins/NdiMedia/commit/693233dd55291a596377500a4f7608dafd6e35e0). I think this issue should be reopened. It seems to be intermittent, such that I can sometimes start and stop playing in PIE mode many times in a row and it will work perfectly, but other times it happens the first time I stop playing just after starting the editor. Sounds like a race condition to me, and may be related to [issue#4](https://github.com/ue4plugins/NdiMedia/issues/4).

**Comment by gmpreussner** [comment]
Closing this one - we can track in https://github.com/ue4plugins/NdiMedia/issues/4
